pipeline {

  agent {
    docker {
        image 'maven:3.9.6-eclipse-temurin-17'
        args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    SONAR_URL        = 'http://20.220.31.252:9000'
    ACR_LOGIN_SERVER = 'ayushacr.azurecr.io'
    ACR_REPO         = 'springboot-app'
    DOCKER_IMAGE     = "${ACR_LOGIN_SERVER}/${ACR_REPO}:${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Ayush3366/Project1BC.git'
        sh 'echo "=== CHECKOUT COMPLETE ==="; ls -R'
      }
    }

    stage('Build & Test') {
      steps {
        sh '''
          echo "=== BUILD & TEST STARTED ==="
          cd spring-boot-app
          mvn clean package
          echo "=== BUILD & TEST COMPLETED ==="
        '''
      }
    }

    stage('Static Code Analysis (SonarQube)') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
            echo "=== SONAR ANALYSIS STARTED ==="
            cd spring-boot-app

            mvn sonar:sonar \
              -Dsonar.token=$SONAR_AUTH_TOKEN \
              -Dsonar.host.url=${SONAR_URL}

            echo "=== SONAR ANALYSIS COMPLETED ==="
          '''
        }
      }
    }

    stage('Install Docker CLI in Agent') {
      steps {
        sh '''
          echo "=== INSTALLING DOCKER CLI ==="
          apt-get update
          apt-get install -y docker.io
          echo "=== DOCKER CLI INSTALLED ==="
        '''
      }
    }

    stage('Build & Push Docker Image to ACR') {
      steps {
        script {

          sh '''
            echo "=== DOCKER BUILD STARTED ==="
            cd spring-boot-app
            docker build -t ${DOCKER_IMAGE} .
            echo "=== DOCKER BUILD COMPLETED ==="
          '''

          def img = docker.image("${DOCKER_IMAGE}")

          docker.withRegistry("https://${ACR_LOGIN_SERVER}", "acr-cred") {
            echo "=== PUSHING IMAGE TO ACR ==="
            img.push()
            echo "=== PUSH COMPLETE ==="
          }
        }
      }
    }
  }

  post {
    success { echo "✅ Pipeline completed successfully! Image: ${DOCKER_IMAGE}" }
    failure { echo "❌ Pipeline failed. Check logs above." }
  }
}
